name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: 'hooray, +1'

          issuesOpened: |
            👋 @{{ author }}
            Merci beaucoup pour votre issue ! 
            Pensez bien à associer cette issue à votre prochaine PR

          pullRequestOpenedOpenedReactions: 'hooray, +1'


          pullRequestOpened: |
            👋 @{{ author }}
            Merci beaucoup pour votre PR. 
            Vous pourrez la fusionner dès que votre enseignant aura fait sa revue !
            